export const inputTheme = {
  input: {
    DEFAULT: [
      'w-full',
      'transition',
      'pl-10',
      'py-2',
      'pr-4',
    ],
    primary: [],
    danger: [
      'rounded bg-white',
      'ring-status-danger-default',
      'text-white',
      'hover:ring-status-danger-dark',
    ],
    white: [
      'rounded',
      'bg-white',
      'text-shifter-purple-primary',
      'hover:ring-shifter-gray-100',
      'hover:text-shifter-purple-700',
    ],
    ghost: [
      'rounded-none',
      'border-b-2',
      'border-transparent',
      'hover:border-shifter-purple-primary',
      'hover:border-b-2',
      'focus:border-shifter-purple-primary',
      'focus:border-b-2',
      'bg-transparent',
      'ring-transparent',
      'text-shifter-purple-primary',
      'focus:ring-0',
    ],
    success: [
      'rounded',
      'bg-white',
      'ring-status-success-default',
      'text-white',
      'hover:ring-status-success-dark',
    ],
  },
};
