extends: 
 - airbnb
 - "plugin:@typescript-eslint/recommended"
parser: '@typescript-eslint/parser'
plugins:
  - react
  - "@typescript-eslint"

rules:
  react/destructuring-assignment: off
  "@typescript-eslint/ban-ts-ignore": off
  "@typescript-eslint/explicit-function-return-type": off
  'import/no-extraneous-dependencies': 
    - 'error'
    -
      devDependencies: ['**/*.spec.ts', '**/*.test.ts', '**/*.spec.tsx', '**/*.test.tsx']
      optionalDependencies: false
  import/extensions:
    - error
    - ignorePackages
    - js: never
      tsx: never
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".ts"
      - ".tsx"
parserOptions:
  sourceType: "module"
  ecmaFeatures:
    jsx: true
settings:
  'import/resolver': 
    node:
      extensions:
        - '.ts'
        - '.tsx'
        - '.js'
        - '.jsx'
      tryExtensions:
        - '.ts'
        - '.tsx'
        - '.js'
        - '.jsx'
  flowtype:
    onlyFilesWithFlowAnnotation: true