sudo: false
language: node_js
node_js:
  - "8"

before_install:
  - npm install codecov.io coveralls

install:
  - npm install

script:
  - npm run lint

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: npm
  email: "info@wp-kyoto.net"
  api_key: "e97c4f32-5ec4-403a-a26d-aa0cd83b6a2a"
  tags: true