export const buttonTheme = {
  button: {
    DEFAULT: [
      'whitespace-nowrap',
      'inline-block',
      'rounded',
      'font-strong',
      'items-center',
      'focus:outline-none',
    ],
    primary: [
      'bg-shifter-purple-500',
      'disabled:bg-shifter-gray-50',
      'disabled:text-shifter-gray-300',
      'focus:bg-shifter-purple-500',
      'focus:ring',
      'focus:ring-focus',
      'hover:bg-shifter-purple-800',
      'px-4',
      'py-2',
      'text-white',
    ],
    danger: [
      'py-2',
      'px-4',
      'bg-status-danger-default',
      'text-white',
      'hover:bg-status-danger-dark',
      'font-strong',
    ],
    white: [
      'py-2',
      'px-4',
      'bg-white',
      'text-shifter-purple-primary',
      'hover:bg-shifter-gray-100',
      'hover:text-shifter-purple-700',
      'font-strong',
    ],
    ghost: [
      'py-2',
      'px-4',
      'bg-transparent',
      'text-shifter-purple-primary',
      'hover:bg-shifter-purple-200',
      'focus:bg-transparent',
      'font-strong',
    ],
    success: [
      'py-2',
      'px-4',
      'bg-status-success-default',
      'text-white',
      'hover:bg-status-success-dark',
      'font-strong',
    ],
    link: ['p-0'],
    outlinePrimary: [
      'py-2',
      'px-4',
      'bg-transparent',
      'ring-2',
      'ring-shifter-purple-primary',
      'hover:bg-shifter-purple-600',
      'hover:text-white',
      'focus:ring',
      'focus:bg-shifter-purple-500',
      'text-shifter-purple-primary',
      'disabled:bg-shifter-gray-200',
      'disabled:text-shifter-gray-300',
      'font-strong',
    ],
  },
};
