export const inputTheme = {
  input: {
    DEFAULT: [''],
    primary: [
      'focus:ring-shifter-purple-primary'
      // 'bg-shifter-purple-primary',
      // 'disabled:bg-shifter-gray-200',
      // 'disabled:text-shifter-gray-300',
      // 'focus:bg-shifter-purple-500',
      // 'focus:ring-shifter-purple-primary',
      // 'hover:bg-shifter-purple-600',
      // 'px-4',
      // 'py-2',
      // 'flex',
      // 'items-center',
    ],
    danger: [
      'bg-status-danger-default',
      'text-white',
      'hover:bg-status-danger-dark',
    ],
    white: [
      'bg-white',
      'text-shifter-purple-primary',
      'hover:bg-shifter-gray-100',
      'hover:text-shifter-purple-700',
    ],
    ghost: [
      'bg-transparent',
      'text-shifter-purple-primary',
      'hover:bg-shifter-purple-200',
      'focus:bg-transparent',
    ],
    success: [
      'py-2',
      'px-4',
      'bg-status-success-default',
      'text-white',
      'hover:bg-status-success-dark',
    ],
    link: ['p-0'],
    outlinePrimary: [
      'py-2',
      'px-4',
      'bg-transparent',
      'ring-2',
      'ring-shifter-purple-primary',
      'hover:bg-shifter-purple-600',
      'hover:text-white',
      'focus:ring',
      'focus:bg-shifter-purple-500',
      'text-shifter-purple-primary',
      'disabled:bg-shifter-gray-200',
      'disabled:text-shifter-gray-300',
    ],
  },
};
